export const EVENTS = {
  SOS_CREATED: "SOS_CREATED",
  SOS_UPDATED: "SOS_UPDATED",
  SOS_STATUS_UPDATED: "SOS_STATUS_UPDATED",

  MECHANIC_ASSIGNED: "MECHANIC_ASSIGNED",
  MECHANIC_LOCATION_UPDATED: "MECHANIC_LOCATION_UPDATED",

  TRACKING_LOCATION: "TRACKING_LOCATION",
  TRIP_COMPLETED: "TRIP_COMPLETED",
};
